// clothingSection.appendChild(img)
// paraElement.appendChild(texnodes)
// clothingSection.appendChild(paraElement)
// brandElement.appendChild(textnodes)
// clothingSection.appendChild(brandElement)
// priceElement.appendChild(priceNodes)
// clothingSection.appendChild(priceElement)